export interface Collection {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  disclaimer: string;
  accentColor: string;
  crystalIds: string[];
  reasons: Record<string, string>; // crystalId -> why it belongs
}

export const COLLECTIONS: Collection[] = [
  {
    slug: "calming",
    title: "The Calming Collection",
    subtitle: "Stones Traditionally Associated with Calm & Anxiety Relief",
    description: "Across cultures and centuries, certain minerals have been consistently associated with calming energy and emotional regulation. Whether through the ritual of holding a smooth stone during stress, the meditative focus of examining a crystal's internal structure, or the cultural weight of a 3,000-year tradition, these stones have earned their reputation as tools for finding stillness.",
    disclaimer: "These associations are cultural traditions, not medical claims. If you experience anxiety, please consult a healthcare professional. Crystals are not substitutes for professional care.",
    accentColor: "#93C5FD",
    crystalIds: ["amethyst", "lepidolite", "blue-lace-agate", "howlite", "smoky-quartz", "celestite", "angelite", "amazonite", "kunzite", "chrysocolla", "smithsonite", "lithium-quartz", "blue-chalcedony"],
    reasons: {
      "amethyst": "The ancient Greeks' anti-anxiety stone. Its name literally means 'not intoxicated' - they believed it calmed the mind.",
      "lepidolite": "Contains lithium, the element used in mood-stabilizing medication. The lithium isn't bioavailable through touch, but the association is notable.",
      "blue-lace-agate": "The quintessential throat-chakra stone. Practitioners use it for calming anxiety around speaking and communication.",
      "howlite": "Associated with slowing an overactive mind. Its white color with gray veining suggests marble calm.",
      "smoky-quartz": "Considered the premier grounding stone. Scottish Highlanders carried cairngorm (smoky quartz) for stability.",
      "celestite": "Named for its heavenly blue color. Placed in bedrooms for peaceful energy.",
      "angelite": "Blue anhydrite associated with gentle, calming energy and angelic connection.",
      "amazonite": "Called the 'hope stone.' Associated with setting healthy boundaries and reducing worry.",
      "kunzite": "Connected to unconditional love and emotional calming. Its gentle pink energy is considered soothing.",
      "chrysocolla": "Cleopatra reportedly carried it for diplomatic calm. Associated with thoughtful communication.",
      "smithsonite": "Called the 'stone of charm.' Its soft pastel colors and botryoidal texture are associated with soothing emotional turbulence and easing anxiety.",
      "lithium-quartz": "Contains visible lithium mica inclusions. The lithium connection and soft mauve color make it one of the most popular calming stones for emotional balance and stress relief.",
      "blue-chalcedony": "Called the 'Speaker's Stone' since Cicero's time. Its soft periwinkle blue and gentle energy calm anxiety around communication and public speaking.",
    },
  },
  {
    slug: "protection",
    title: "The Protection Collection",
    subtitle: "Stones with the Longest Traditions of Protective Use",
    description: "Protection stones represent one of the oldest and most universal uses of minerals in human culture. Roman soldiers rubbed hematite on their bodies before battle. Aztec priests carved obsidian mirrors to ward off evil. Turquoise has been sewn into horse bridles, set in sword hilts, and worn as amulets across four continents. Whatever your relationship with these traditions, the cultural history is rich and genuinely ancient.",
    disclaimer: "Protective associations are cultural and historical traditions. Crystal Almanac documents these traditions without endorsing supernatural claims.",
    accentColor: "#1C1917",
    crystalIds: ["black-tourmaline", "apache-tear", "obsidian", "hematite", "tiger-eye", "labradorite", "smoky-quartz", "amethyst", "turquoise", "malachite", "shungite", "nephrite", "tigers-iron", "bronzite"],
    reasons: {
      "black-tourmaline": "The most popular protection stone in the modern crystal market. Pyroelectric and piezoelectric properties were observed centuries before they were scientifically explained.",
      "apache-tear": "Carried for comfort during grief and loss. The Apache warrior legend makes it one of the most emotionally resonant protection stones.",
      "obsidian": "Aztec priests used obsidian mirrors for scrying and protection. The volcanic glass has been associated with shielding across Mesoamerican cultures for millennia.",
      "hematite": "Roman soldiers rubbed it on their bodies believing it made them invincible. The name means 'blood stone' in Greek.",
      "tiger-eye": "Ancient Egyptian deity statues had tiger's eye eyes. The chatoyant shimmer was believed to represent all-seeing divine vision.",
      "labradorite": "Inuit legend says the Northern Lights were trapped in coastal rocks until a warrior freed them with his spear - the remaining light became labradorite.",
      "smoky-quartz": "Scottish Highlanders set smoky quartz (cairngorm) in dagger handles and brooches for protection in battle and travel.",
      "amethyst": "Medieval European soldiers wore amethyst amulets for protection in battle. The stone has been associated with sobriety and clear-headedness since antiquity.",
      "turquoise": "One of the most universally protective stones. Persian horsemen attached it to bridles, believing it prevented falls. Native American peoples used it in ceremony for thousands of years.",
      "malachite": "Ancient Egyptians associated malachite with protective goddess Hathor. Used as eye paint partly for its perceived protective qualities.",
      "shungite": "Peter the Great established the first Russian spa at Karelian shungite deposits. Russian folk tradition associates it with purification.",
      "nephrite": "Called the 'stone of heaven' in Chinese culture for over 5,000 years. The toughest natural material, used as protective amulets and ceremonial objects across Chinese, Maori, and Mesoamerican civilizations.",
      "tigers-iron": "Combines three classic protection and grounding stones - tiger eye, hematite, and red jasper - in a single 2.5-billion-year-old formation. Triple the protective association in one stone.",
      "bronzite": "Called the 'bronze shield' for its metallic shimmer and reputation for deflecting negative energy back to its source. The warm, grounded energy builds self-assurance under pressure.",
    },
  },
  {
    slug: "love",
    title: "The Love Collection",
    subtitle: "Stones Associated with Love, Relationships & the Heart",
    description: "The connection between pink and green stones and matters of the heart stretches across cultures and centuries. Rose quartz was placed in tombs by ancient Egyptians as a love token. Emerald was Cleopatra's obsession. Rhodochrosite carries the Incan tradition of petrified rulers' blood. These associations aren't random - they reflect deep cultural patterns connecting color, beauty, and emotional meaning.",
    disclaimer: "These are cultural and historical traditions. Crystals do not cause romantic attraction or heal relationships. They can, however, serve as meaningful tokens and meditation tools.",
    accentColor: "#EC4899",
    crystalIds: ["rose-quartz", "coral", "rhodochrosite", "emerald", "morganite", "kunzite", "rhodonite", "pink-opal", "watermelon-tourmaline", "chrysoprase", "unakite", "cobaltocalcite", "tugtupite", "rubellite", "thulite", "pink-amethyst", "mangano-calcite"],
    reasons: {
      "coral": "Italian cornicello tradition, Tibetan sacred treasure, and one of the oldest love-protection amulets in Mediterranean culture.",
      "rose-quartz": "The universal love stone. Ancient Egyptians placed rose quartz face masks in tombs. Romans and Greeks associated it with Aphrodite/Venus.",
      "rhodochrosite": "Called 'Rosa del Inca' - the Incan rose. Argentina's national gemstone, associated with passionate, compassionate love.",
      "emerald": "Cleopatra's stone. Associated with successful love and loyalty across cultures from Egyptian to Mughal to European.",
      "morganite": "Named after J.P. Morgan. Rising as an engagement ring alternative - its gentle pink and beryl durability make it practical and beautiful.",
      "kunzite": "Named by Tiffany's gemologist. Connected to unconditional love and vulnerability. Its light-sensitivity is interpreted as a metaphor for protecting tender feelings.",
      "rhodonite": "The 'rescue stone.' Associated with emotional healing after heartbreak, particularly forgiveness and rebuilding trust.",
      "pink-opal": "Peru's national stone. Inca tradition connects it to Pachamama (Earth Mother) energy. Considered the gentlest heart stone.",
      "watermelon-tourmaline": "Pink core + green rim maps to the heart chakra's dual energy: emotional love (pink) and growth (green).",
      "chrysoprase": "Alexander the Great wore chrysoprase into battle. Associated with Venus in medieval tradition.",
      "unakite": "Green epidote + pink feldspar. Used in fertility-related traditions and for balancing giving and receiving in relationships.",
      "cobaltocalcite": "One of the most vivid pink minerals on Earth. Cobalt creates an intense magenta that practitioners associate with unconditional love and emotional opening.",
      "tugtupite": "Called the 'stone of true love' in Greenlandic Inuit tradition. Legend says it glows when lovers are near. Its color deepens in light, symbolizing love that grows stronger.",
      "rubellite": "The red tourmaline of deep, passionate love. Maintains its vivid red in any light - associated with love that doesn't shift or fade with changing circumstances.",
      "thulite": "Norway's pink zoisite, named after the ancient Nordic land of Thule. Associated with joy, pleasure, and the celebration of life's emotional richness.",
      "pink-amethyst": "The rare Patagonian rose quartz with crystalline points. Combines amethyst's calming energy with a gentle pink that opens the heart. A newer discovery already beloved for nurturing emotional tenderness.",
      "mangano-calcite": "Called the stone of divine love. Its soft baby-pink from manganese creates one of the gentlest heart-healing energies. Often recommended as a first crystal for emotional healing work.",
    },
  },
  {
    slug: "creativity",
    title: "The Creative Collection",
    subtitle: "Stones Associated with Creative Expression & Inspiration",
    description: "Artists, writers, and musicians have reached for specific stones for centuries. Carnelian was the signet stone of architects and builders in ancient Egypt. Citrine sat on the desks of Renaissance merchants who valued both creative problem-solving and prosperity. The connection between warm-colored stones and creative fire runs deep in Western and Eastern traditions alike.",
    disclaimer: "Creative associations are cultural traditions. Crystals don't generate ideas, but they can serve as focus objects during creative practice.",
    accentColor: "#F97316",
    crystalIds: ["carnelian", "citrine", "sunstone", "fire-agate", "ametrine", "fluorite", "labradorite", "azurite", "wulfenite", "sphalerite", "fire-opal", "tangerine-quartz", "spessartine-garnet", "orange-calcite"],
    reasons: {
      "carnelian": "Ancient Egyptian architects and builders wore carnelian. Associated with bold creative action and the courage to present work publicly.",
      "citrine": "Called 'the merchant's stone.' Associated with both creative vision and the ability to manifest ideas into reality.",
      "sunstone": "Contains actual metallic copper. The internal fire is associated with creative warmth, enthusiasm, and leadership in artistic pursuits.",
      "fire-agate": "Thin-film interference creates literal fire inside the stone. Associated with creative passion and the courage to reveal hidden beauty.",
      "ametrine": "Half amethyst, half citrine. The dual nature represents integrating creative intuition (purple) with practical execution (gold).",
      "fluorite": "Called 'the genius stone' by some practitioners. Its wide color range and geometric crystal forms are associated with mental clarity and creative organization.",
      "labradorite": "The flash of color from within represents the spark of inspiration emerging from the subconscious.",
      "azurite": "Renaissance painters ground it into blue pigment. Literally the color of creative expression in medieval and Renaissance art.",
      "wulfenite": "Called 'the painter's stone.' Its vivid orange and thin tabular form are associated with artistic vision.",
      "sphalerite": "Has three times diamond's fire. Associated with creative brilliance and the energy to pursue ambitious projects.",
      "fire-opal": "The Aztec 'sun stone,' associated with Quetzalcoatl and creative fire. Its vivid body color glows like a live ember - pure creative intensity in stone form.",
      "tangerine-quartz": "Iron-kissed quartz connected to the sacral chakra. Associated with playful creativity, sensory inspiration, and the joy of making.",
      "spessartine-garnet": "Called 'mandarin garnet' for its electric orange. Associated with creative confidence, bold self-expression, and the energy to start ambitious projects.",
      "orange-calcite": "Liquid sunshine in mineral form. Its vivid orange energizes the sacral chakra and is associated with breaking through creative blocks, sparking imagination, and finding joy in the creative process.",
    },
  },
  {
    slug: "grounding",
    title: "The Grounding Collection",
    subtitle: "Stones Associated with Stability, Focus & Earth Connection",
    description: "Grounding stones share a pattern: they're typically dark, dense, and often metallic or earthy in appearance. This isn't coincidence. The heaviest, most earth-connected minerals naturally suggest stability. When you hold a piece of hematite and feel its unexpected weight, or run your thumb across a polished obsidian surface, the physical experience itself is grounding. These stones have been used for centering practices across cultures.",
    disclaimer: "Grounding associations are cultural traditions. The physical experience of holding a dense, smooth stone can be genuinely calming through tactile focus, but this is a sensory effect, not a metaphysical one.",
    accentColor: "#78716C",
    crystalIds: ["hematite", "black-tourmaline", "obsidian", "smoky-quartz", "tiger-eye", "jasper", "garnet", "bloodstone", "shungite", "magnetite", "petrified-wood", "tigers-iron", "red-jasper", "kambaba-jasper"],
    reasons: {
      "hematite": "Specific gravity 5.26 - it feels shockingly heavy. The physical weight creates an immediate sense of substance and connection to earth.",
      "black-tourmaline": "The most popular grounding crystal. Its striated crystal faces and solid black color reinforce the 'rooted' association.",
      "obsidian": "Volcanic glass - literally born from the Earth's interior. Its solid, grounding quality has been recognized since the Stone Age.",
      "smoky-quartz": "Scotland's national gemstone. The Gaelic tradition of carrying cairngorm for grounding is centuries old.",
      "tiger-eye": "The chatoyant shimmer requires slow, focused observation. The act of watching the light move is itself a grounding practice.",
      "jasper": "Called 'the supreme nurturer.' Jasper varieties have been used as grounding stones across virtually every culture with access to the mineral.",
      "garnet": "Deep red, dense, and ancient. Associated with root chakra stability and physical vitality across Hindu and Western traditions.",
      "bloodstone": "Roman gladiators carried it for endurance. The combination of earth-green with blood-red spots symbolizes life force rooted in the physical world.",
      "shungite": "2 billion years old. The sheer geological age of this carbon-rich rock connects it to deep Earth history.",
      "magnetite": "Literally magnetic. Lodestone's physical pull on iron is the most dramatic demonstration of Earth energy in any mineral.",
      "petrified-wood": "Ancient trees turned to stone over millions of years. The ultimate symbol of patience, deep time, and earth's transformative power. Holding 225-million-year-old wood grounds you in geological time.",
      "tigers-iron": "2.5 billion years old - formed during the Great Oxidation Event. Combines three grounding minerals (tiger eye, hematite, red jasper) into one ancient stone.",
      "red-jasper": "Called the 'supreme nurturer.' Roman soldiers carried it for endurance. The most universally used grounding stone, with a tradition spanning every culture that had access to it.",
      "kambaba-jasper": "Dark green orbicular stone from Madagascar, hundreds of millions of years old. Its deep earth tones and ancient geological age connect it to primal grounding energy and ancestral wisdom.",
    },
  },
  {
    slug: "abundance",
    title: "The Abundance Collection",
    subtitle: "Stones Traditionally Associated with Prosperity & Success",
    description: "Gold-colored and green stones have been associated with wealth across cultures for obvious symbolic reasons - they resemble the things they're meant to attract. But the traditions run deeper than simple color association. Jade has been more valuable than gold in Chinese culture for millennia. Pyrite's metallic luster earned it the name 'fool's gold' precisely because people confused it with the real thing. These stones represent humanity's long relationship with material aspiration.",
    disclaimer: "Prosperity associations are cultural traditions. No mineral attracts money. These stones can serve as reminders of financial goals during intentional practice.",
    accentColor: "#F59E0B",
    crystalIds: ["citrine", "pyrite", "jade", "aventurine", "gold", "tiger-eye", "malachite", "sunstone", "emerald", "moss-agate", "tsavorite", "imperial-topaz", "chrysoberyl", "golden-healer-quartz"],
    reasons: {
      "citrine": "Called 'the merchant's stone.' Shopkeepers historically placed citrine in cash registers. Associated with abundance and manifestation.",
      "pyrite": "'Fool's gold' - its resemblance to gold is so convincing it fooled prospectors. Associated with attracting wealth and recognizing opportunity.",
      "jade": "More valuable than gold in imperial Chinese culture. Associated with prosperity, longevity, and nobility for over 5,000 years.",
      "aventurine": "Called 'the stone of opportunity.' Green aventurine is one of the most popular prosperity stones in the crystal market.",
      "gold": "The eternal metal. Every civilization in human history has associated gold with wealth, power, and divine favor.",
      "tiger-eye": "Associated with practical decision-making and financial wisdom. The chatoyant eye is said to see through deception in business.",
      "malachite": "Used as a merchant's talisman in the Middle Ages. Its banded green patterns were associated with growing wealth.",
      "sunstone": "Contains actual copper. The warm metallic shimmer is associated with solar energy, leadership, and attracting success.",
      "emerald": "The gem of royalty and wealth. Cleopatra, Mughal emperors, and European monarchs all hoarded emeralds as symbols of power.",
      "moss-agate": "European farmers placed moss agate in fields for abundant harvests. The oldest agricultural prosperity stone tradition in Western culture.",
      "tsavorite": "The vivid green grossular garnet rivaling emerald. Discovered in 1967 and championed by Tiffany's, it represents modern gem-world abundance and the rewards of persistent searching.",
      "imperial-topaz": "Named for Russian czars who claimed the finest golden-pink topaz exclusively for royalty. The 'imperial' designation itself is a statement of abundance and divine right.",
      "chrysoberyl": "Cat's eye chrysoberyl was one of the most prized talismans in ancient India and Sri Lanka, believed to protect wealth and ward off financial misfortune.",
      "golden-healer-quartz": "Iron-kissed quartz radiating solar energy. Considered a master manifestation stone that channels universal life force through the solar plexus, the chakra of personal power and abundance.",
    },
  },
  {
    slug: "communication",
    title: "The Communication Collection",
    subtitle: "Stones Associated with Expression, Truth & Clear Thinking",
    description: "Blue and blue-green stones dominate the communication category across crystal traditions - a pattern that maps to throat chakra associations in Hindu tradition and to sky/heaven symbolism in Western and Middle Eastern cultures. The association between blue stones and truth-telling is remarkably consistent: lapis lazuli was the stone of Ma'at (Egyptian goddess of truth), turquoise was the 'truth stone' in Persian culture, and aquamarine was carried by sailors who needed to speak clearly under pressure.",
    disclaimer: "Communication associations are cultural traditions. Crystals do not improve speaking ability. They can serve as focus objects for communication-related intentions.",
    accentColor: "#38BDF8",
    crystalIds: ["blue-lace-agate", "aquamarine", "sodalite", "amazonite", "lapis-lazuli", "chrysocolla", "kyanite", "turquoise", "larimar", "celestite", "blue-apatite", "indicolite", "shattuckite", "blue-topaz"],
    reasons: {
      "blue-lace-agate": "The quintessential communication stone. Its soft blue color and gentle banding are associated with calm, clear self-expression.",
      "aquamarine": "The 'sailor's stone.' Associated with courage under pressure and clear communication in difficult situations.",
      "sodalite": "Called 'the poet's stone.' Associated with articulating complex ideas and finding the right words.",
      "amazonite": "Found in Tutankhamun's tomb. Associated with honest communication and setting clear boundaries.",
      "lapis-lazuli": "The stone of the Egyptian goddess Ma'at, who represented truth. Ground into pigment for medieval illuminated manuscripts.",
      "chrysocolla": "Cleopatra's diplomatic stone. Associated with negotiation, teaching, and compassionate communication.",
      "kyanite": "Said to 'never need cleansing.' Associated with cutting through confusion and speaking truth without fear.",
      "turquoise": "Truth stone in Persian culture. Given as a gift symbolizing friendship and honest exchange across many traditions.",
      "larimar": "Dominican Republic's stone. Associated with calm expression and translating spiritual insight into words.",
      "celestite": "Named 'celestial' for its sky color. Associated with angelic communication and expressing higher truths.",
      "blue-apatite": "Named from the Greek 'to deceive' because it mimics other gems. Associated with motivation, goal clarity, and articulating ambitions - the communication of vision.",
      "indicolite": "The rare blue tourmaline. Combines tourmaline's protective energy with the throat-chakra association of blue stones. Connected to expressing difficult truths with compassion.",
      "shattuckite": "Named after Arizona's Shattuck Mine. One of the deepest blue copper silicates. Associated with channeling, mediumship, and receiving clear spiritual messages for articulation.",
      "blue-topaz": "Hard, durable, and clear. The three shades (Sky, Swiss, London) map to gentle expression, confident communication, and deep wisdom. Its clarity symbolizes transparent, honest speech.",
    },
  },
  {
    slug: "meditation",
    title: "The Meditation Collection",
    subtitle: "Stones Used as Focus Objects in Contemplative Practice",
    description: "Using stones as meditation aids is one of the oldest and most pragmatic applications of crystals. The practice is straightforward: holding a smooth, cool stone provides tactile focus that anchors attention. Examining a crystal's internal structure under light gives the mind a genuinely complex visual object to explore. These are attention tools, not magic - and they work for the same reason worry stones, prayer beads, and fidget tools work: they give the body something to do while the mind settles.",
    disclaimer: "Meditation associations are cultural traditions. The tactile and visual focus benefits of holding minerals during meditation are practical, not supernatural.",
    accentColor: "#A78BFA",
    crystalIds: ["amethyst", "tibetan-quartz", "clear-quartz", "selenite", "labradorite", "fluorite", "apophyllite", "scolecite", "phantom-quartz", "lemurian-quartz", "danburite", "lodolite", "optical-calcite", "hackmanite", "auralite-23"],
    reasons: {
      "tibetan-quartz": "Hand-collected at 5,000 meters in the Himalayas. Tibetan Buddhist monks have used crystals in meditation practice for centuries.",
      "amethyst": "Tibetan Buddhist tradition uses amethyst rosaries for meditation. Its purple color and accessible price make it the most widely used meditation crystal.",
      "clear-quartz": "The most versatile meditation stone. Its internal structures (phantoms, veils, rainbows) provide complex visual focus during contemplative practice.",
      "selenite": "Named after Selene, Greek moon goddess. Its translucent, luminous quality creates a calming visual focus in low light.",
      "labradorite": "The shifting iridescent play of color provides an ever-changing visual meditation focus. No two viewing angles are identical.",
      "fluorite": "Geometric cubic and octahedral crystals provide satisfying tactile objects. The color range offers variety for different meditation intentions.",
      "apophyllite": "Exceptional transparency acts as a natural meditation lens. Practitioners look into the crystal as a focus practice.",
      "scolecite": "The radiating needle sprays provide a mandala-like visual structure for meditation focus.",
      "phantom-quartz": "The visible 'ghost' crystal inside provides a meditation focus on growth, layers, and the passage of time.",
      "lemurian-quartz": "The horizontal striations provide a tactile meditation practice - running a finger along the ridges as a focus technique.",
      "danburite": "Called 'angel stone.' Its clarity and gentle energy are associated with deep, peaceful meditation states.",
      "lodolite": "Garden quartz with miniature landscapes trapped inside. Each specimen is a unique meditation world - practitioners gaze into the internal 'gardens' as a visualization focus.",
      "optical-calcite": "Viking sunstone with double refraction. Place it over text and see two images - a meditation on perception, duality, and seeing beyond the obvious.",
      "hackmanite": "The color-changing sodalite. Shifts from violet to white and back, providing a literally transforming meditation focus. The impermanence of its color teaches present-moment awareness.",
      "auralite-23": "1.2 billion years old with up to 23 different mineral inclusions. Practitioners report uniquely strong meditation experiences. The extreme age and mineral complexity provide a deep, multi-layered focus object.",
    },
  },
];

export function getCollectionBySlug(slug: string): Collection | undefined {
  return COLLECTIONS.find((c) => c.slug === slug);
}

export function getAllCollectionSlugs(): string[] {
  return COLLECTIONS.map((c) => c.slug);
}
